#!/bin/bash


# These steps can be done in whatever flow you want later. They exist here
# to ensure that a single setup step can comprehensively set everything up.
stack build
stack exec setup -- --include-dependencies --include-custom-scripts

# Install vim plugins. This can't be done from the haskell script because
# vim won't start within the spawned processes for some reason.
nvim +PlugInstall +PlugClean! +qall

echo "Activate powerline fonts for non-ascii text in iterm2 if necessary - 
https://github.com/powerline/fonts"
echo "Finished! Please restart your terminal and everything should work :)"
