#!/bin/bash

# Haskell Stack tool and GHC
command -v stack || curl -sSL https://get.haskellstack.org/ | sh

# These steps can be done in whatever flow you want later. They exist here
# to ensure that a single setup step can comprehensively set everything up.
stack build
stack exec setup-exe -- --dependencies
