name: dotfiles
root: ~/dotfiles

windows:
    - dotfiles:
          layout: main-vertical
          panes:
              - vim
              - null
    - interview:
          root: ~/projects/interview
          layout: main-vertical
          panes:
              - vim
              - null
