name: open-source
windows:
- river:
    layout: main-vertical
    panes:
    - vim
    - watch-dev
    - null
    root: ~/projects/river
- river-bitbucket:
    layout: main-vertical
    panes:
    - vim
    - null
    root: ~/projects/river-bitbucket-test
- river-github:
    layout: main-vertical
    panes:
    - vim
    - null
    root: ~/projects/river-github-test
- react-elm:
    layout: main-vertical
    panes:
    - vim
    - npm run start
    - null
    root: ~/projects/react-elm
- todo-app:
    layout: main-vertical
    panes:
    - vim
    - pscid -I src
    - parcel src/index.html
    root: ~/projects/todo-app
- haskell-presentation:
    layout: main-vertical
    panes:
    - vim
    - null
    - null
    root: ~/projects/haskell-presentation
- scripts:
    layout: main-vertical
    panes:
    - vim
    - null
    - null
    root: ~/projects/scripts
- purescript-test:
    layout: main-vertical
    panes:
    - vim
    - null
    - null
    root: ~/projects/purescript-test
- terraform-test:
    layout: main-vertical
    panes:
    - vim
    - null
    - null
    root: ~/projects/terraform-test
