source ~/.shell/aliases

export ZSH=$HOME/.oh-my-zsh

plugins=(
   autojump
   fzf
)

ZSH_THEME="cloud"

source $ZSH/oh-my-zsh.sh

export EDITOR='nvim'
export VISUAL='nvim'

# Path
export PATH=$HOME/.local/bin:$PATH # Haskell Stack executables

export FZF_DEFAULT_COMMAND='ag --hidden -g ""'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
