source ~/.shell/aliases

export ZSH=$HOME/dotfiles/.installations/robbyrussell/oh-my-zsh

plugins=(
   autojump
   fzf
   tmuxinator
   zsh-completions
)

export TERM="xterm-256color"

ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(background_jobs time)
POWERLEVEL9K_SHORTEN_STRATEGY="Default"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2

autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

# Tmuxinator
export TMUXINATOR_CONFIG="$HOME/dotfiles/src/configs/tmuxinator"
source ~/dotfiles/.installations/tmuxinator/tmuxinator/completion/tmuxinator.zsh

export EDITOR='nvim'
export VISUAL='nvim'

# Path
export PATH=$HOME/.local/bin:$PATH # Haskell Stack executables

export FZF_DEFAULT_COMMAND='ag --hidden -g ""'

# Rbenv shims and stuff
eval "$(rbenv init -)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
