#!/bin/bash

REPOS=(
    "anamnesis-report-renderer"
    "flow-app"
    "start-client"
    "start-server"
    "start-questionnaire-components"
    "react-elm"
)
DIR="$HOME/projects/doctrin"

clone() {
    git clone "git@bitbucket.org:doctrin/$1.git"
}

if [[ $1 == "clone" ]]; then
    if ! [ -e $DIR ]; then
        mkdir -p $DIR
    fi

    cd $DIR

    for REPO in ${REPOS[@]}; do
        if ! [ -e "$DIR/$REPO" ]; then
            clone $REPO
        fi 
    done
fi
